/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from;

import com.sun.org.apache.xerces.internal.impl.dv.xs.DateDV;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.BaseCalendar;
import java.util.Calendar;
import java.util.Date;
/**
 *
 * @author AHSAN
 */
public class frmPengembalian extends javax.swing.JFrame {
private Connection con;
    private Statement st;
    private ResultSet RsPengembalian;
    private ResultSet RsRental;
    private ResultSet RsMobil;
    private ResultSet RsStatus;
    private ResultSet RsPenyewa;
    private ResultSet RsM;
    private String sql="";
    
    private String tanggal1,tanggal2,idpengembalian,idrental,namapenyewa,namamobil,bm,status,idmobil,idpenyewa;
    private int harga,hari,total;
    /**
     * Creates new form frmPengembalian
     */
    public frmPengembalian() {
        initComponents();
        KoneksiPengembalian();
        TampilData(sql);
        tanggalrental.setEnabled(false);
    }
    
    private void KoneksiPengembalian(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rental_mobil", "root","");
            System.out.println("Koneksi Berhasil");
        } catch (Exception e){
            System.out.println("Koneksi Gagal \n"+e);
        }
    }
    
    private void TampilData (String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("ID PENGEMBALIAN");
        datalist.addColumn("ID RENTAL");
        datalist.addColumn("ID PENYEWA");
        datalist.addColumn("ID MOBIL");
        datalist.addColumn("TANGGAL KEMBALI");
        datalist.addColumn("LAMA");
        datalist.addColumn("TOTAL BAYAR");
        try{
            int i = 1;
            st=con.createStatement();
            RsPengembalian=st.executeQuery("select * from tb_pengembalian");
            while (RsPengembalian.next())
                datalist.addRow(new Object[]{
                (""+i++),
                RsPengembalian.getString(1), RsPengembalian.getString(2),
                RsPengembalian.getString(3), RsPengembalian.getString(4),
                RsPengembalian.getString(6), RsPengembalian.getString(7),
                RsPengembalian.getString(8)});
            
            TABEL3.setModel(datalist);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil \n"+e.getMessage());
        }
    }
    
    private void bersih(){
        Txt_harga.setText("");
        Txt_id_mobil.setText("");
        Txt_id_pengembalian.setText("");
        Txt_id_penyewa.setText("");
        Txt_lama.setText("");
        Txt_nama_mobil.setText("");
        Txt_nama_penyewa.setText("");
        Txt_status.setText("");
        Txt_total.setText("");
        Cmb_status.setSelectedItem("PILIH");
        Cmb_id_rental.setSelectedItem("");
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BTN_EDIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL3 = new javax.swing.JTable();
        BTN_BATAL = new javax.swing.JButton();
        BTN_HAPUS = new javax.swing.JButton();
        BTN_KELUAR = new javax.swing.JButton();
        BTN_SIMPAN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Txt_id_pengembalian = new javax.swing.JTextField();
        Cmb_status = new javax.swing.JComboBox();
        Cmb_id_rental = new javax.swing.JComboBox();
        Txt_id_penyewa = new javax.swing.JTextField();
        Txt_id_mobil = new javax.swing.JTextField();
        Txt_nama_penyewa = new javax.swing.JTextField();
        Txt_nama_mobil = new javax.swing.JTextField();
        Txt_harga = new javax.swing.JTextField();
        tanggalrental = new com.toedter.calendar.JDateChooser();
        tanggalkembali = new com.toedter.calendar.JDateChooser();
        Txt_lama = new javax.swing.JTextField();
        Txt_total = new javax.swing.JTextField();
        Txt_status = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/back2.png"))); // NOI18N

        BTN_EDIT.setBackground(new java.awt.Color(255, 255, 255));
        BTN_EDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/edit.png"))); // NOI18N
        BTN_EDIT.setText("EDIT");
        BTN_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EDITActionPerformed(evt);
            }
        });

        TABEL3.setBackground(new java.awt.Color(204, 204, 204));
        TABEL3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PENGEMBALIAN", "ID RENTAL", "ID PENYEWA", "ID MOBIL", "TANGGAL KEMBALI", "LAMA", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(TABEL3);

        BTN_BATAL.setBackground(new java.awt.Color(255, 255, 255));
        BTN_BATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save-and-close.png"))); // NOI18N
        BTN_BATAL.setText("BATAL");
        BTN_BATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BATALActionPerformed(evt);
            }
        });

        BTN_HAPUS.setBackground(new java.awt.Color(255, 255, 255));
        BTN_HAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/delete.png"))); // NOI18N
        BTN_HAPUS.setText("HAPUS");
        BTN_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HAPUSActionPerformed(evt);
            }
        });

        BTN_KELUAR.setBackground(new java.awt.Color(255, 255, 255));
        BTN_KELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/close.png"))); // NOI18N
        BTN_KELUAR.setText("KELUAR");
        BTN_KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_KELUARActionPerformed(evt);
            }
        });

        BTN_SIMPAN.setBackground(new java.awt.Color(255, 255, 255));
        BTN_SIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save.png"))); // NOI18N
        BTN_SIMPAN.setText("SIMPAN");
        BTN_SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIMPANActionPerformed(evt);
            }
        });

        jLabel1.setText("ID PENGEMBALIAN");

        Txt_id_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_id_pengembalianActionPerformed(evt);
            }
        });
        Txt_id_pengembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_id_pengembalianKeyPressed(evt);
            }
        });

        Cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "KEMBALI" }));
        Cmb_status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_statusItemStateChanged(evt);
            }
        });
        Cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_statusActionPerformed(evt);
            }
        });

        Cmb_id_rental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_id_rentalItemStateChanged(evt);
            }
        });
        Cmb_id_rental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_id_rentalActionPerformed(evt);
            }
        });

        Txt_id_penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_id_penyewaActionPerformed(evt);
            }
        });
        Txt_id_penyewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_id_penyewaKeyPressed(evt);
            }
        });

        Txt_id_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_id_mobilActionPerformed(evt);
            }
        });
        Txt_id_mobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_id_mobilKeyPressed(evt);
            }
        });

        Txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_hargaActionPerformed(evt);
            }
        });
        Txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_hargaKeyPressed(evt);
            }
        });

        tanggalrental.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalrentalPropertyChange(evt);
            }
        });

        tanggalkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalkembaliPropertyChange(evt);
            }
        });

        Txt_lama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_lamaActionPerformed(evt);
            }
        });
        Txt_lama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_lamaKeyPressed(evt);
            }
        });

        Txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_totalActionPerformed(evt);
            }
        });
        Txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_totalKeyPressed(evt);
            }
        });

        Txt_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_statusActionPerformed(evt);
            }
        });
        Txt_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_statusKeyPressed(evt);
            }
        });

        jLabel3.setText("PILIHAN KEMBALI");

        jLabel4.setText("ID RENTAL");

        jLabel5.setText("ID PENYEWA");

        jLabel6.setText("ID MOBIL");

        jLabel7.setText("NAMA PENYEWA");

        jLabel8.setText("NAMA MOBIL");

        jLabel9.setText("HARGA RENTAL");

        jLabel10.setText("TANGGAL RENTAL");

        jLabel11.setText("LAMA");

        jLabel12.setText("TANGGAL KEMBALI");

        jLabel13.setText("TOTAL BAYAR");

        jLabel14.setText("STATUS");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Home.png"))); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_nama_mobil)
                                    .addComponent(Txt_nama_penyewa)
                                    .addComponent(Txt_id_pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(Cmb_status, 0, 124, Short.MAX_VALUE)
                                    .addComponent(Cmb_id_rental, 0, 124, Short.MAX_VALUE)
                                    .addComponent(Txt_id_penyewa, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(Txt_id_mobil, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tanggalrental, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggalkembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Txt_status, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_total, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_lama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTN_BATAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTN_EDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTN_HAPUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTN_SIMPAN))
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTN_KELUAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(Txt_id_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cmb_id_rental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_id_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_nama_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(tanggalrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(tanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_SIMPAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_BATAL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_EDIT)
                                .addGap(6, 6, 6)
                                .addComponent(BTN_HAPUS))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_KELUAR)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EDITActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        idrental=Cmb_id_rental.getItemAt(Cmb_id_rental.getSelectedIndex()).toString();
        idmobil=String.valueOf(Txt_id_mobil.getText());
        idpenyewa=String.valueOf(Txt_id_penyewa.getText());
        namapenyewa=String.valueOf(Txt_nama_penyewa.getText());
        namamobil=String.valueOf(Txt_nama_mobil.getText());
        harga=Integer.parseInt(Txt_harga.getText());
        hari=Integer.parseInt(Txt_lama.getText());
        total=Integer.parseInt(Txt_total.getText());
        status=Cmb_status.getItemAt(Cmb_status.getSelectedIndex()).toString();
        try {
            sql="update tb_pengembalian set tgl_kembali='"+ tanggal2 +"',lama='"+ hari +"',total_bayar='"+ total +"',status='"+ status +"' "
                    + "where id_pengembalian = '"+ idpengembalian +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Edit \n"+e.getMessage());
        }
    }//GEN-LAST:event_BTN_EDITActionPerformed

    private void BTN_SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIMPANActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        idrental=Cmb_id_rental.getItemAt(Cmb_id_rental.getSelectedIndex()).toString();
        idmobil=String.valueOf(Txt_id_mobil.getText());
        idpenyewa=String.valueOf(Txt_id_penyewa.getText());
        namapenyewa=String.valueOf(Txt_nama_penyewa.getText());
        namamobil=String.valueOf(Txt_nama_mobil.getText());
        harga=Integer.parseInt(Txt_harga.getText());
        hari=Integer.parseInt(Txt_lama.getText());
        total=Integer.parseInt(Txt_total.getText());
        status=Cmb_status.getItemAt(Cmb_status.getSelectedIndex()).toString();
        if (Cmb_status.getSelectedItem().equals("SELESAI")){
            JOptionPane.showMessageDialog(null, "MOBIL SUDAH DIKEMBALIKAN");
            bersih();
        }
        else if (Txt_id_pengembalian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ID PENGEMBALIAN MASIH KOSONG");
        }
        else {
            try {
                sql = sql="INSERT INTO tb_pengembalian(id_pengembalian, id_rental,"
                + "id_mobil, id_penyewa, tgl_rental, "
                + "tgl_kembali, lama, total_bayar, status)VALUE"
                + "('"+ idpengembalian +"','"+ idrental +"','"+ idmobil +"','"+ idpenyewa +"',"
                + "'"+ tanggal1 +"','"+ tanggal2 +"','"+ hari +"','"+ total +"','"+ status +"')";
                st=con.createStatement();
                st.execute(sql);
                bersih();
                TampilData(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan \n"+e.getMessage());
            }
            try {
                String sql="select * from tb_mobil";
                Statement st = con.createStatement();
                RsMobil=st.executeQuery(sql);
                status = "READY";
                sql="update tb_mobil set status = '"+ status +"' where id_mobil ='"+ idmobil +"'";
                st=con.createStatement();
                st.execute(sql);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
            }
            try {
                status = "SELESAI";
                sql="update tb_rental set status = '"+ status +"' where id_rental = '"+ idrental +"'";
                st=con.createStatement();
                st.execute(sql);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
            }
        }
    }//GEN-LAST:event_BTN_SIMPANActionPerformed

    private void BTN_KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KELUARActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BTN_KELUARActionPerformed

    private void BTN_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HAPUSActionPerformed
        // TODO add your handling code here:
        idrental=String.valueOf(Txt_id_pengembalian.getText());
        try {
            sql="delete from tb_rental where id_rental='"+ idrental +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+e.getMessage());
        }
    }//GEN-LAST:event_BTN_HAPUSActionPerformed

    private void BTN_BATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BATALActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_BTN_BATALActionPerformed

    private void Txt_id_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_id_pengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_pengembalianActionPerformed

    private void Txt_id_pengembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_id_pengembalianKeyPressed
        // TODO add your handling code here:
        idpengembalian=Txt_id_pengembalian.getText();
        int tekanenter=evt.getKeyCode();
        if(tekanenter==10){
            try{
                String sql = "select * from tb_rental";
                Statement st = con.createStatement();
                RsRental = st.executeQuery(sql);
                while (RsRental.next()){
                    String Aliaskd = RsRental.getString("id_rental");
                    Cmb_id_rental.addItem(Aliaskd);
                    Cmb_status.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Gagal menampilkan id mobil \n"
                    +e.getMessage());
            }
            try {
                sql = "select * from tb_pengembalian "
                        + "where id_pengembalian='"+ idpengembalian +"'";
                st = con.createStatement();
                RsPengembalian = st.executeQuery(sql);
                while (RsPengembalian.next()){
                    Cmb_id_rental.setSelectedItem(RsPengembalian.getString("id_rental"));
                    Txt_id_mobil.setText(RsPengembalian.getString("id_mobil"));
                    tanggalrental.setDate(RsPengembalian.getDate("tgl_rental"));
                    tanggalkembali.setDate(RsPengembalian.getDate("tgl_kembali"));
                    Txt_lama.setText(RsPengembalian.getString("lama"));
                    Txt_total.setText(RsPengembalian.getString("total_bayar"));
                    Txt_status.setText(RsPengembalian.getString("status"));
                    JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Data Tidak Ditemukan  \n"
                    +e.getMessage());

            }
        }
    }//GEN-LAST:event_Txt_id_pengembalianKeyPressed

    private void Cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_statusActionPerformed
        // TODO add your handling code here:
        if(Cmb_status.getSelectedItem() =="KEMBALI"){
            Cmb_id_rental.removeAllItems();
            Cmb_id_rental.addItem("PILIH");
            try {
                status=String.valueOf(Cmb_status.getSelectedItem());
                status = "SEWA";
                String sql = "select * from tb_rental where status = '"+ status +"'";
                Statement st = con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                    String AliasID = RsRental.getString("id_rental");
                    Cmb_id_rental.addItem(AliasID);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan id rental"+e.getMessage());
            }
        }

    }//GEN-LAST:event_Cmb_statusActionPerformed

    private void Cmb_id_rentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_id_rentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_id_rentalActionPerformed

    private void Txt_id_penyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_id_penyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_penyewaActionPerformed

    private void Txt_id_penyewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_id_penyewaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_penyewaKeyPressed

    private void Txt_id_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_id_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_mobilActionPerformed

    private void Txt_id_mobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_id_mobilKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_mobilKeyPressed

    private void Txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_hargaActionPerformed

    private void Txt_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_hargaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_hargaKeyPressed

    private void tanggalrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalrentalPropertyChange
        // TODO add your handling code here:
        if(tanggalrental.getDate() !=null){
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tanggal1=format.format(tanggalrental.getDate());
        }
    }//GEN-LAST:event_tanggalrentalPropertyChange

    private void tanggalkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalkembaliPropertyChange
        // TODO add your handling code here:
        if(tanggalkembali.getDate() !=null){
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tanggal2=format.format(tanggalkembali.getDate());
        }
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date pinjam = tanggalrental.getDate();
            Date kembali = tanggalkembali.getDate();
            long pinjam1 = pinjam.getTime();
            long kembali1 = kembali.getTime();
            long diff = kembali1 - pinjam1;
            long lama = diff/(24*60*60*1000);
            Txt_lama.setText(Long.toString(lama));
            harga=Integer.parseInt(Txt_harga.getText());
            hari=Integer.parseInt(Txt_lama.getText());
            total=harga*hari;
            Txt_total.setText(String.valueOf(total));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tanggalkembaliPropertyChange

    private void Txt_lamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_lamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_lamaActionPerformed

    private void Txt_lamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_lamaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_lamaKeyPressed

    private void Txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_totalActionPerformed

    private void Txt_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_totalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_totalKeyPressed

    private void Txt_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_statusActionPerformed

    private void Txt_statusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_statusKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_statusKeyPressed

    private void Cmb_id_rentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_id_rentalItemStateChanged
        // TODO add your handling code here:
        try {
            sql="select * from tb_rental where "
                    + "id_rental='"+ Cmb_id_rental.getSelectedItem() +"'";
            st=con.createStatement();
            RsRental=st.executeQuery(sql);
            while (RsRental.next()){
                Txt_id_mobil.setText(RsRental.getString("id_mobil"));
                Txt_id_penyewa.setText(RsRental.getString("id_penyewa"));
                Txt_nama_penyewa.setText(RsRental.getString("nama_penyewa"));
                tanggalrental.setDate(RsRental.getDate(7));
                Txt_nama_mobil.setText(RsRental.getString("nama_mobil"));
                Txt_harga.setText(RsRental.getString("harga_rental"));
                Txt_status.setText(RsRental.getString("status"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Cmb_id_rentalItemStateChanged

    private void Cmb_statusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_statusItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_statusItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MENU_UTAMA home = new MENU_UTAMA();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BATAL;
    private javax.swing.JButton BTN_EDIT;
    private javax.swing.JButton BTN_HAPUS;
    private javax.swing.JButton BTN_KELUAR;
    private javax.swing.JButton BTN_SIMPAN;
    private javax.swing.JComboBox Cmb_id_rental;
    private javax.swing.JComboBox Cmb_status;
    private javax.swing.JTable TABEL3;
    private javax.swing.JTextField Txt_harga;
    private javax.swing.JTextField Txt_id_mobil;
    private javax.swing.JTextField Txt_id_pengembalian;
    private javax.swing.JTextField Txt_id_penyewa;
    private javax.swing.JTextField Txt_lama;
    private javax.swing.JTextField Txt_nama_mobil;
    private javax.swing.JTextField Txt_nama_penyewa;
    private javax.swing.JTextField Txt_status;
    private javax.swing.JTextField Txt_total;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser tanggalkembali;
    private com.toedter.calendar.JDateChooser tanggalrental;
    // End of variables declaration//GEN-END:variables
}
