

package main.server;
import main.login;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.koneksi;


/**
 *
 * @author AHSAN
 */
public class frmMobil extends javax.swing.JFrame {
    private Connection con;
    private Statement st;
    private ResultSet RsMobil;
    private String sql="";
    
    private String id,mobil,merk,bm,status;
    private int harga; 

    /**
     * Creates new form frmMobil
     */
    public frmMobil() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = koneksi.koneksi();
        TampilData(sql);
        bersih();
        
    }
   
    
    private void TampilData (String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("NO");
        datalist.addColumn("ID_MOBIL");
        datalist.addColumn("NAMA MOBIL");
        datalist.addColumn("MEREK MOBIL");
        datalist.addColumn("BM MOBIL");
        datalist.addColumn("HARGA RENTAL");
        datalist.addColumn("STATUS");
        try{
            int i = 1;
            st=con.createStatement();
            RsMobil=st.executeQuery("select * from tb_mobil");
            while (RsMobil.next())
                datalist.addRow(new Object[]{
                    (i++),
                RsMobil.getString(1), RsMobil.getString(2),
                RsMobil.getString(3), RsMobil.getString(4),
                RsMobil.getString(5), RsMobil.getString(6)});
            TABEL.setModel(datalist);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil \n"+e.getMessage());
        }
    }
    
    private void bersih(){
        Txt_bm.setText("");
        Txt_harga.setText("");
        txt_id_mobil.setText("");
        Txt_merk.setText("");
        Txt_nama_mobil.setText("");
        Cmb_status.setSelectedItem("PILIH");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cmb_status = new javax.swing.JComboBox();
        BTN_SIMPAN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jLabel2 = new javax.swing.JLabel();
        BTN_EDIT = new javax.swing.JButton();
        BTN_BATAL = new javax.swing.JButton();
        BTN_HAPUS = new javax.swing.JButton();
        BTN_KELUAR = new javax.swing.JButton();
        Txt_nama_mobil = new javax.swing.JTextField();
        Txt_bm = new javax.swing.JTextField();
        Txt_harga = new javax.swing.JTextField();
        Txt_merk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_id_mobil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "READY", "NOT READY" }));
        Cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_statusActionPerformed(evt);
            }
        });

        BTN_SIMPAN.setBackground(new java.awt.Color(255, 255, 255));
        BTN_SIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save.png"))); // NOI18N
        BTN_SIMPAN.setText("TAMBAH");
        BTN_SIMPAN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIMPANActionPerformed(evt);
            }
        });

        TABEL.setBackground(new java.awt.Color(204, 204, 204));
        TABEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAMA MOBIL", "MEREK MOBIL", "BM MOBIL", "HARGA RENTAL", "STATUS"
            }
        ));
        TABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABELMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABEL);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/addmobil2.png"))); // NOI18N

        BTN_EDIT.setBackground(new java.awt.Color(255, 255, 255));
        BTN_EDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/edit.png"))); // NOI18N
        BTN_EDIT.setText("EDIT");
        BTN_EDIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EDITActionPerformed(evt);
            }
        });

        BTN_BATAL.setBackground(new java.awt.Color(255, 255, 255));
        BTN_BATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save-and-close.png"))); // NOI18N
        BTN_BATAL.setText("BATAL");
        BTN_BATAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_BATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BATALActionPerformed(evt);
            }
        });

        BTN_HAPUS.setBackground(new java.awt.Color(255, 255, 255));
        BTN_HAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/delete.png"))); // NOI18N
        BTN_HAPUS.setText("HAPUS");
        BTN_HAPUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HAPUSActionPerformed(evt);
            }
        });

        BTN_KELUAR.setBackground(new java.awt.Color(255, 255, 255));
        BTN_KELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/close.png"))); // NOI18N
        BTN_KELUAR.setText("KELUAR");
        BTN_KELUAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_KELUARActionPerformed(evt);
            }
        });

        Txt_nama_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nama_mobilActionPerformed(evt);
            }
        });

        Txt_bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_bmActionPerformed(evt);
            }
        });

        Txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_hargaActionPerformed(evt);
            }
        });

        Txt_merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_merkActionPerformed(evt);
            }
        });
        Txt_merk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_merkKeyPressed(evt);
            }
        });

        jLabel3.setText("NAMA MOBIL");

        jLabel4.setText("BM MOBIL");

        jLabel5.setText("STATUS");

        jLabel6.setText("MEREK MOBIL");

        jLabel7.setText("HARGA RENTAL");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Home.png"))); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_id_mobil.setEnabled(false);

        jLabel1.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_nama_mobil)
                    .addComponent(Txt_bm)
                    .addComponent(Txt_harga)
                    .addComponent(Txt_merk)
                    .addComponent(Cmb_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BTN_SIMPAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_BATAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_EDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_HAPUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_KELUAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_SIMPAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_BATAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_EDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_HAPUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_bm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(6, 6, 6)
                .addComponent(BTN_KELUAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_statusActionPerformed

    private void BTN_SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIMPANActionPerformed
        // TODO add your handling code here:
//      id=String.valueOf(Txt_id_mobil.getText());
        mobil=String.valueOf(Txt_nama_mobil.getText());
        merk=String.valueOf(Txt_merk.getText());
        bm=String.valueOf(Txt_bm.getText());
        harga =Integer.valueOf(Txt_harga.getText());
        status=String.valueOf(Cmb_status.getSelectedItem());
        if (Cmb_status.getSelectedItem().equals("PILIH")){
            JOptionPane.showMessageDialog(null, "STATUS BELUM DIPILIH");
        }
        else if (Cmb_status.getSelectedItem().equals("NOT READY")) {
            JOptionPane.showMessageDialog(null, "MOBIL SUDAH DIRENTAL");
        }else{
        try{
            sql="INSERT INTO tb_mobil(nama_mobil, "
                    + "merek_mobil, bm_mobil, harga_rental, "
                    + "status)value"
                    + "('"+ mobil+"','"+ merk +"','"+ bm +"',"
                    + "'"+ harga +"','"+ status +"')";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan \n"+e.getMessage());
        }
        }
    }//GEN-LAST:event_BTN_SIMPANActionPerformed

    private void BTN_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EDITActionPerformed
                id=String.valueOf(txt_id_mobil.getText());
                mobil=String.valueOf(Txt_nama_mobil.getText());
                merk=String.valueOf(Txt_merk.getText());
                bm=String.valueOf(Txt_bm.getText());
                harga=Integer.parseInt(Txt_harga.getText());
                status=String.valueOf(Cmb_status.getSelectedItem());
                try {
                    sql="update tb_mobil set nama_mobil='"+ mobil +"',merek_mobil='"+ merk +"',BM_mobil='"+ bm +"',harga_rental='"+ harga +"',status='"+ status +"' where id_mobil = '"+ id +"'";
                    st=con.createStatement();
                    st.execute(sql);
                    bersih();
                    TampilData(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal di Edit \n"+e.getMessage());
                }
       
    }//GEN-LAST:event_BTN_EDITActionPerformed

    private void BTN_BATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BATALActionPerformed
        // TODO add your handling code here:
        bersih();
        
    }//GEN-LAST:event_BTN_BATALActionPerformed

    private void BTN_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HAPUSActionPerformed
        // TODO add your handling code here:
//        id=String.valueOf(Txt_id_mobil.getText());
        try {
            // TODO add your handling code here:
            id=String.valueOf(txt_id_mobil.getText());
            sql="DELETE FROM tb_mobil"
                    +" where id_mobil='"+ id +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+ex.getMessage());
        }
       
    }//GEN-LAST:event_BTN_HAPUSActionPerformed

    private void BTN_KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KELUARActionPerformed
        // TODO add your handling code here:
        login masuk = new login();
        masuk.setLocationRelativeTo(null);
        masuk.setVisible(true);
        dispose();
    }//GEN-LAST:event_BTN_KELUARActionPerformed

    private void Txt_nama_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nama_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nama_mobilActionPerformed

    private void Txt_bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_bmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_bmActionPerformed

    private void Txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_hargaActionPerformed

    private void Txt_merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_merkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_merkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainServer home = new MainServer();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_merkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_merkKeyPressed
        // TODO add your handling code here:
//        id=Txt_id_mobil.getText();
        mobil=Txt_nama_mobil.getText();
//        try {
//            // TODO add your handling code here:
//            id=String.valueOf(RsMobil.getString("id_mobil"));
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, "Gagal pada database" + ex);
//        }
        int tekanenter=evt.getKeyCode();
        if(tekanenter==10){
            try{
                sql="select * from tb_mobil "
                        + "where nama_mobil='"+ mobil +"'";
                st=con.createStatement();
                RsMobil=st.executeQuery(sql);
                while (RsMobil.next()){
                    Txt_nama_mobil.setText(RsMobil.getString("nama_mobil"));
                    Txt_merk.setText(RsMobil.getString(3));
                    Txt_bm.setText(RsMobil.getString(4));
                    Txt_harga.setText(RsMobil.getString(5));
                    Cmb_status.setSelectedItem(RsMobil.getString(6));
                    JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan \n"
                +e.getMessage());
                Txt_nama_mobil.requestFocus();
            }
        }
    }//GEN-LAST:event_Txt_merkKeyPressed

    private void TABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABELMouseClicked
        // TODO add your handling code here:
        int baris = TABEL.rowAtPoint(evt.getPoint());
        String id = TABEL.getValueAt(baris, 1).toString();
        txt_id_mobil.setText(id);
        String mobil = TABEL.getValueAt(baris, 2).toString();
        Txt_nama_mobil.setText(mobil);
        String merk = TABEL.getValueAt(baris, 3).toString();
        Txt_merk.setText(merk);
        String bm = TABEL.getValueAt(baris, 4).toString();
        Txt_bm.setText(bm);
        String harga = TABEL.getValueAt(baris, 5).toString();
        Txt_harga.setText(harga);
        String status = TABEL.getValueAt(baris, 6).toString();
        Cmb_status.setSelectedItem(status);
      
    }//GEN-LAST:event_TABELMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BATAL;
    private javax.swing.JButton BTN_EDIT;
    private javax.swing.JButton BTN_HAPUS;
    private javax.swing.JButton BTN_KELUAR;
    private javax.swing.JButton BTN_SIMPAN;
    private javax.swing.JComboBox Cmb_status;
    private javax.swing.JTable TABEL;
    private javax.swing.JTextField Txt_bm;
    private javax.swing.JTextField Txt_harga;
    private javax.swing.JTextField Txt_merk;
    private javax.swing.JTextField Txt_nama_mobil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_id_mobil;
    // End of variables declaration//GEN-END:variables
}
