/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.server;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import main.koneksi;
import main.login;
/**
 *
 * @author AHSAN
 */
public class frmPengembalian extends javax.swing.JFrame {
private Connection con = null;
    private Statement st;
    private ResultSet RsPengembalian;
    private ResultSet RsRental;
    private ResultSet RsMobil;
    private ResultSet RsStatus;
    private ResultSet RsPenyewa;
    private ResultSet RsM;
    private String sql="";
    
    private String tanggal1,tanggal2,idpengembalian,idrental,namapenyewa,namamobil,bm,status,idmobil,idpenyewa;
    private int harga,hari,total;
    /**
     * Creates new form frmPengembalian
     */
    public frmPengembalian() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = koneksi.koneksi();
        TampilData(sql);
        tanggalrental.setEnabled(false);
    }
    
   
    private void TampilData (String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("NO");
        datalist.addColumn("ID PENGEMBALIAN");
        datalist.addColumn("ID RENTAL");
        datalist.addColumn("PENYEWA");
        datalist.addColumn("MOBIL");
        datalist.addColumn("TANGGAL KEMBALI");
        datalist.addColumn("LAMA");
        datalist.addColumn("TOTAL BAYAR");
        datalist.addColumn("STATUS");
        try{
            int i = 1;
            st=con.createStatement();
            RsPengembalian=st.executeQuery("select * from tb_pengembalian");
            while (RsPengembalian.next())
                datalist.addRow(new Object[]{
                (""+i++),
                RsPengembalian.getString(1), RsPengembalian.getString(2),
                RsPengembalian.getString(3), RsPengembalian.getString(4),
                RsPengembalian.getString(6), RsPengembalian.getString(7),
                RsPengembalian.getString(8), RsPengembalian.getString(9)});
            
            TABEL3.setModel(datalist);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil \n"+e.getMessage());
        }
    }
    
    private void bersih(){
        Txt_harga.setText("");
        Txt_id_pengembalian.setText("");
        Txt_lama.setText("");
        Txt_nama_mobil.setText("");
        Txt_nama_penyewa.setText("");
        Txt_status.setText("");
        Txt_total.setText("");
        tanggalkembali.setDate(null);
        tanggalrental.setDate(null);
        Cmb_status.setSelectedItem("PILIH");
        Cmb_id_rental.setSelectedItem("PILIH");
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BTN_EDIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL3 = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        BTN_BATAL = new javax.swing.JButton();
        BTN_HAPUS = new javax.swing.JButton();
        BTN_KELUAR = new javax.swing.JButton();
        BTN_SIMPAN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Txt_id_pengembalian = new javax.swing.JTextField();
        Cmb_status = new javax.swing.JComboBox();
        Cmb_id_rental = new javax.swing.JComboBox();
        Txt_nama_penyewa = new javax.swing.JTextField();
        Txt_nama_mobil = new javax.swing.JTextField();
        Txt_harga = new javax.swing.JTextField();
        tanggalrental = new com.toedter.calendar.JDateChooser();
        tanggalkembali = new com.toedter.calendar.JDateChooser();
        Txt_lama = new javax.swing.JTextField();
        Txt_total = new javax.swing.JTextField();
        Txt_status = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/back2.png"))); // NOI18N

        BTN_EDIT.setBackground(new java.awt.Color(255, 255, 255));
        BTN_EDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/edit.png"))); // NOI18N
        BTN_EDIT.setText("EDIT");
        BTN_EDIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EDITActionPerformed(evt);
            }
        });

        TABEL3.setBackground(new java.awt.Color(204, 204, 204));
        TABEL3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PENGEMBALIAN", "ID RENTAL", "PENYEWA", "MOBIL", "TANGGAL KEMBALI", "LAMA", "TOTAL", "STATUS"
            }
        ));
        TABEL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABEL3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TABEL3MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(TABEL3);

        BTN_BATAL.setBackground(new java.awt.Color(255, 255, 255));
        BTN_BATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save-and-close.png"))); // NOI18N
        BTN_BATAL.setText("BATAL");
        BTN_BATAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_BATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BATALActionPerformed(evt);
            }
        });

        BTN_HAPUS.setBackground(new java.awt.Color(255, 255, 255));
        BTN_HAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/delete.png"))); // NOI18N
        BTN_HAPUS.setText("HAPUS");
        BTN_HAPUS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HAPUSActionPerformed(evt);
            }
        });

        BTN_KELUAR.setBackground(new java.awt.Color(255, 255, 255));
        BTN_KELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/close.png"))); // NOI18N
        BTN_KELUAR.setText("KELUAR");
        BTN_KELUAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_KELUARActionPerformed(evt);
            }
        });

        BTN_SIMPAN.setBackground(new java.awt.Color(255, 255, 255));
        BTN_SIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save.png"))); // NOI18N
        BTN_SIMPAN.setText("TAMBAH");
        BTN_SIMPAN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIMPANActionPerformed(evt);
            }
        });

        jLabel1.setText("ID PENGEMBALIAN");

        Txt_id_pengembalian.setEnabled(false);
        Txt_id_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_id_pengembalianActionPerformed(evt);
            }
        });
        Txt_id_pengembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_id_pengembalianKeyPressed(evt);
            }
        });

        Cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "KEMBALI" }));
        Cmb_status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_statusItemStateChanged(evt);
            }
        });
        Cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_statusActionPerformed(evt);
            }
        });

        Cmb_id_rental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_id_rentalItemStateChanged(evt);
            }
        });
        Cmb_id_rental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_id_rentalActionPerformed(evt);
            }
        });

        Txt_nama_penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nama_penyewaActionPerformed(evt);
            }
        });

        Txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_hargaActionPerformed(evt);
            }
        });
        Txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_hargaKeyPressed(evt);
            }
        });

        tanggalrental.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalrentalPropertyChange(evt);
            }
        });

        tanggalkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalkembaliPropertyChange(evt);
            }
        });

        Txt_lama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_lamaActionPerformed(evt);
            }
        });
        Txt_lama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_lamaKeyPressed(evt);
            }
        });

        Txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_totalActionPerformed(evt);
            }
        });
        Txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_totalKeyPressed(evt);
            }
        });

        Txt_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_statusActionPerformed(evt);
            }
        });
        Txt_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_statusKeyPressed(evt);
            }
        });

        jLabel3.setText("PILIHAN KEMBALI");

        jLabel4.setText("ID RENTAL");

        jLabel7.setText("NAMA PENYEWA");

        jLabel8.setText("NAMA MOBIL");

        jLabel9.setText("HARGA RENTAL");

        jLabel10.setText("TANGGAL RENTAL");

        jLabel11.setText("LAMA");

        jLabel12.setText("TANGGAL KEMBALI");

        jLabel13.setText("TOTAL BAYAR");

        jLabel14.setText("STATUS");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/Home.png"))); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_nama_mobil)
                    .addComponent(Txt_nama_penyewa)
                    .addComponent(Cmb_status, 0, 131, Short.MAX_VALUE)
                    .addComponent(Txt_id_pengembalian)
                    .addComponent(Cmb_id_rental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tanggalkembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Txt_status, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_total, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_lama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_harga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalrental, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_KELUAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_BATAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_HAPUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_EDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_SIMPAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTN_SIMPAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_BATAL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_EDIT)
                                .addGap(6, 6, 6)
                                .addComponent(BTN_HAPUS))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_KELUAR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(tanggalrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(tanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_id_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cmb_id_rental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Txt_nama_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainServer home = new MainServer();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_statusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_statusKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_statusKeyPressed

    private void Txt_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_statusActionPerformed

    private void Txt_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_totalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_totalKeyPressed

    private void Txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_totalActionPerformed

    private void Txt_lamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_lamaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_lamaKeyPressed

    private void Txt_lamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_lamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_lamaActionPerformed

    private void tanggalkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalkembaliPropertyChange
        // TODO add your handling code here:
        if(tanggalkembali.getDate() !=null){
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tanggal2=format.format(tanggalkembali.getDate());
        }
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date pinjam = tanggalrental.getDate();
            Date kembali = tanggalkembali.getDate();
            long pinjam1 = pinjam.getTime();
            long kembali1 = kembali.getTime();
            long diff = kembali1 - pinjam1;
            long lama = diff/(24*60*60*1000);
            Txt_lama.setText(Long.toString(lama));
            harga=Integer.parseInt(Txt_harga.getText());
            hari=Integer.parseInt(Txt_lama.getText());
            total=harga*hari;
            Txt_total.setText(String.valueOf(total));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tanggalkembaliPropertyChange

    private void tanggalrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalrentalPropertyChange
        // TODO add your handling code here:
        if(tanggalrental.getDate() !=null){
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            tanggal1=format.format(tanggalrental.getDate());
        }
    }//GEN-LAST:event_tanggalrentalPropertyChange

    private void Txt_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_hargaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_hargaKeyPressed

    private void Txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_hargaActionPerformed

    private void Cmb_id_rentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_id_rentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_id_rentalActionPerformed

    private void Cmb_id_rentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_id_rentalItemStateChanged
        // TODO add your handling code here:
        try {
            sql="select * from tb_rental where "
            + "id_rental='"+ Cmb_id_rental.getSelectedItem() +"'";
            st=con.createStatement();
            RsRental=st.executeQuery(sql);
            while (RsRental.next()){
                Txt_nama_penyewa.setText(RsRental.getString("nama_penyewa"));
                tanggalrental.setDate(RsRental.getDate(5));
                Txt_nama_mobil.setText(RsRental.getString("nama_mobil"));
                Txt_harga.setText(RsRental.getString("harga_rental"));
                Txt_status.setText(RsRental.getString("status"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Cmb_id_rentalItemStateChanged

    private void Cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_statusActionPerformed
        // TODO add your handling code here:
        if(Cmb_status.getSelectedItem() =="KEMBALI"){
            Cmb_id_rental.removeAllItems();
            Cmb_id_rental.addItem("PILIH");
            try {
                status=String.valueOf(Cmb_status.getSelectedItem());
                status = "SEWA";
                String sql = "select * from tb_rental where status = '"+ status +"'";
                Statement st = con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                    String AliasID = RsRental.getString("id_rental");
                    Cmb_id_rental.addItem(AliasID);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Menampilkan id rental"+e.getMessage());
            }
        }
    }//GEN-LAST:event_Cmb_statusActionPerformed

    private void Cmb_statusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_statusItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_statusItemStateChanged

    private void Txt_id_pengembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_id_pengembalianKeyPressed
        // TODO add your handling code here:
        idpengembalian=Txt_id_pengembalian.getText();
        int tekanenter=evt.getKeyCode();
        if(tekanenter==10){
            try{
                String sql = "select * from tb_rental";
                Statement st = con.createStatement();
                RsRental = st.executeQuery(sql);
                while (RsRental.next()){
                    String Aliaskd = RsRental.getString("id_rental");
                    Cmb_id_rental.addItem(Aliaskd);
                    Cmb_status.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Gagal menampilkan id mobil \n"
                    +e.getMessage());
            }
            try {
                sql = "select * from tb_pengembalian "
                + "where id_pengembalian='"+ idpengembalian +"'";
                st = con.createStatement();
                RsPengembalian = st.executeQuery(sql);
                while (RsPengembalian.next()){
                    Cmb_id_rental.setSelectedItem(RsPengembalian.getString("id_rental"));
                    tanggalrental.setDate(RsPengembalian.getDate("tgl_rental"));
                    tanggalkembali.setDate(RsPengembalian.getDate("tgl_kembali"));
                    Txt_lama.setText(RsPengembalian.getString("lama"));
                    Txt_total.setText(RsPengembalian.getString("total_bayar"));
                    Txt_status.setText(RsPengembalian.getString("status"));
                    JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Data Tidak Ditemukan  \n"
                    +e.getMessage());

            }
        }
    }//GEN-LAST:event_Txt_id_pengembalianKeyPressed

    private void Txt_id_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_id_pengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_id_pengembalianActionPerformed

    private void BTN_SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIMPANActionPerformed
        // TODO add your handling code here:
//      idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        idrental=Cmb_id_rental.getItemAt(Cmb_id_rental.getSelectedIndex()).toString();
        namapenyewa=String.valueOf(Txt_nama_penyewa.getText());
        namamobil=String.valueOf(Txt_nama_mobil.getText());
        harga=Integer.parseInt(Txt_harga.getText());
        hari=Integer.parseInt(Txt_lama.getText());
        total=Integer.parseInt(Txt_total.getText());
        status=Cmb_status.getItemAt(Cmb_status.getSelectedIndex()).toString();
        if (Cmb_status.getSelectedItem().equals("SELESAI")){
            JOptionPane.showMessageDialog(null, "MOBIL SUDAH DIKEMBALIKAN");
            bersih();
        } else {
            try {
                sql = sql="INSERT INTO tb_pengembalian(id_rental,"
                + "mobil, penyewa, tgl_rental, "
                + "tgl_kembali, lama, total_bayar, status)VALUE"
                + "('"+ idrental +"','"+ namamobil +"','"+ namapenyewa +"',"
                + "'"+ tanggal1 +"','"+ tanggal2 +"','"+ hari +"','"+ total +"','"+ status +"')";
                st=con.createStatement();
                st.execute(sql);
                bersih();
                TampilData(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan \n"+e.getMessage());
            }
            try {
                status = "READY";
                sql="update tb_mobil set status = '"+ status +"' where nama_mobil ='"+ namamobil +"'";
                st=con.createStatement();
                st.execute(sql);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
            }
            try {
                status = "SELESAI";
                sql="update tb_rental set status = '"+ status +"' where id_rental = '"+ idrental +"'";
                st=con.createStatement();
                st.execute(sql);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
            }
            try {
                status = "READY";
                sql="update tb_penyewa set status = '"+ status +"' where nama_penyewa = '"+ namapenyewa +"'";
                st=con.createStatement();
                st.execute(sql);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Maaf Error"+e.getMessage());
            }
        }
    }//GEN-LAST:event_BTN_SIMPANActionPerformed

    private void BTN_KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KELUARActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Keluar ?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
           if (response == JOptionPane.YES_OPTION) {
                 login masuk = new login();
                 masuk.setLocationRelativeTo(null);
                 masuk.setVisible(true);
                 dispose();
            } 
    }//GEN-LAST:event_BTN_KELUARActionPerformed

    private void BTN_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HAPUSActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        int response = JOptionPane.showConfirmDialog(null, "Hapus Data ?", "Konfirmasi",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
           if (response == JOptionPane.YES_OPTION) {
                 try {
                    sql="delete from tb_pengembalian where id_pengembalian='"+ idpengembalian +"'";
                    st=con.createStatement();
                    st.execute(sql);
                    bersih();
                    TampilData(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+e.getMessage());
                        }
            } 
    }//GEN-LAST:event_BTN_HAPUSActionPerformed

    private void BTN_BATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BATALActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_BTN_BATALActionPerformed

    private void BTN_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EDITActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        idrental=Cmb_id_rental.getItemAt(Cmb_id_rental.getSelectedIndex()).toString();
        namapenyewa=String.valueOf(Txt_nama_penyewa.getText());
        namamobil=String.valueOf(Txt_nama_mobil.getText());
        harga=Integer.parseInt(Txt_harga.getText());
        hari=Integer.parseInt(Txt_lama.getText());
        total=Integer.parseInt(Txt_total.getText());
        status=Cmb_status.getItemAt(Cmb_status.getSelectedIndex()).toString();
        try {
            sql="update tb_pengembalian set tgl_kembali='"+ tanggal2 +"',lama='"+ hari +"',total_bayar='"+ total +"',status='"+ status +"' "
            + "where id_pengembalian = '"+ idpengembalian +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Edit \n"+e.getMessage());
        }
    }//GEN-LAST:event_BTN_EDITActionPerformed

    private void TABEL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABEL3MouseClicked
        // TODO add your handling code here:int baris = TABEL3.rowAtPoint(evt.getPoint());
        int baris = TABEL3.rowAtPoint(evt.getPoint());
        String status = TABEL3.getValueAt(baris, 8).toString();
        Cmb_status.setSelectedItem(status);
        
        String id_pengembalian = TABEL3.getValueAt(baris, 1).toString();
        Txt_id_pengembalian.setText(id_pengembalian);
        String id_rental = TABEL3.getValueAt(baris, 2).toString();
        try {
            String sql = "select id_rental from tb_pengembalian where id_rental = '"+ id_rental +"'";
                Statement st = con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                    Cmb_id_rental.addItem(RsRental.getString("id_rental"));  
                    Cmb_id_rental.setSelectedItem(RsRental.getString("id_rental"));
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        String nama = TABEL3.getValueAt(baris, 3).toString();
        Txt_nama_penyewa.setText(nama);
        String mobil = TABEL3.getValueAt(baris, 4).toString();
        Txt_nama_mobil.setText(mobil);
        String lama = TABEL3.getValueAt(baris, 6).toString();
        Txt_lama.setText(lama);
        
        String stringDate = TABEL3.getValueAt(baris, 5).toString();
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = format.parse(stringDate);
            tanggalkembali.setDate(date);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        String total = TABEL3.getValueAt(baris, 7).toString();
        Txt_total.setText(total);
        
        Txt_status.setText(status);
        try {
            String sql = "select tgl_rental from tb_rental where id_rental = '"+ id_rental +"'";
                Statement st = con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                      String tglRent = RsRental.getString("tgl_rental");
                      Date tgl = format.parse(tglRent);
                      tanggalrental.setDate(tgl);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try {
            String sql = "select harga_rental from tb_rental where id_rental = '"+ id_rental +"'";
                Statement st = con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                      String hrgRent = RsRental.getString("harga_rental");
                      Txt_harga.setText(hrgRent);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_TABEL3MouseClicked

    private void Txt_nama_penyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nama_penyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nama_penyewaActionPerformed

    private void TABEL3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABEL3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TABEL3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BATAL;
    private javax.swing.JButton BTN_EDIT;
    private javax.swing.JButton BTN_HAPUS;
    private javax.swing.JButton BTN_KELUAR;
    private javax.swing.JButton BTN_SIMPAN;
    private javax.swing.JComboBox Cmb_id_rental;
    private javax.swing.JComboBox Cmb_status;
    private javax.swing.JTable TABEL3;
    private javax.swing.JTextField Txt_harga;
    private javax.swing.JTextField Txt_id_pengembalian;
    private javax.swing.JTextField Txt_lama;
    private javax.swing.JTextField Txt_nama_mobil;
    private javax.swing.JTextField Txt_nama_penyewa;
    private javax.swing.JTextField Txt_status;
    private javax.swing.JTextField Txt_total;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser tanggalkembali;
    private com.toedter.calendar.JDateChooser tanggalrental;
    // End of variables declaration//GEN-END:variables
}
